//enemyArray
export default [
    {
        name: "Oviraptor",
        image: "oviraptor.png",
        loot: "OVIRAPTORLEGLEGARMARMTAILHEADCREST",
        hp: 200,
        maxHp: 200,
        armor: 2,
        dodge: 10,
        speed: 5,
        resistance: 5,
        attacks: [{name: "slash", dmg: 20}, {name: "bite", dmg: 30}],
    },
    {
        name: "Ankylosaurus",
        image: "Anky.png",
        loot: "ANKYLOSAURUSHEADLEGLEGLEGLEG",
        hp: 400,
        maxHp: 400,
        armor: 20,
        dodge: 0,
        speed: 4,
        resistance: 10,
        attacks: [{name: "tail smash", dmg: 20}, {name: "Bludgeon", dmg: 30}],
    },
    {
        name: "Archaeopteryx",
        image: "archaeopteryx.png",
        loot: "ARCHAEOPTERYXHEADWINGWINGLEGLEG",
        hp: 250,
        maxHp: 250,
        armor: 2,
        dodge: 20,
        speed: 7,
        resistance: 5,
        attacks: [{name: "slash", dmg: 20}, {name: "peck", dmg: 30}],
    },
    {
        name: "Brachiosaurus",
        image: "brachiosaurus.png",
        loot: "BRACHIOSAURUSBRACHIOSAURUSLEGLEGLEGLEG",
        hp: 800,
        maxHp: 800,
        armor: 2,
        dodge: 0,
        speed: 2,
        resistance: 20,
        attacks: [{name: "Stomp", dmg: 30}, {name: "tail smash", dmg: 40}],
    },
    {
        name: "Dimetrodon",
        image: "demitro.png",
        loot: "DIMETRODONHEADLEGLEGLEGLEGSPINESAIL",
        hp: 350,
        maxHp: 350,
        armor: 2,
        dodge: 6,
        speed: 6,
        resistance: 5,
        attacks: [{name: "Bite", dmg: 20}, {name: "tail smash", dmg: 30}],
    },
    {
        name: "Necknomingia",
        image: "necknomingia.png",
        loot: "NECKNOMINGIAHEADARMARMLEGLEG",
        hp: 200,
        maxHp: 200,
        armor: 2,
        dodge: 20,
        speed: 8,
        resistance: 5,
        attacks: [{name: "slash", dmg: 20}, {name: "peck", dmg: 30}],
    },
    {
        name: "Pachycephalosaurus",
        image: "Pachycephalosaurus.png",
        loot: "PACHYCEPHALOSAURUSARMARMLEGLEGLEGLEG",
        hp: 300,
        maxHp: 300,
        armor: 5,
        dodge: 5,
        speed: 6,
        resistance: 5,
        attacks: [{name: "Head butt", dmg: 40}, {name: "charge", dmg: 30}],
    },
    {
        name: "Stegosaurus",
        image: "stego.png",
        loot: "STEGOSAURUSLEGLEGLEGLEGPLATES",
        hp: 300,
        maxHp: 300,
        armor: 5,
        dodge: 4,
        speed: 6,
        resistance: 5,
        attacks: [{name: "tail swipe", dmg: 40}, {name: "bash", dmg: 30}],
    },
    {
        name: "Tyrannosaurus Rex",
        image: "T-rex.png",
        loot: "TYRANNOSAURUSREXHEADMOUTHMOUTHARMARMLEGLEG",
        hp: 600,
        maxHp: 600,
        armor: 5,
        dodge: 3,
        speed: 6,
        resistance: 5,
        attacks: [{name: "Bite", dmg: 40}, {name: "Stomp", dmg: 30}],
    },
    {
        name: "Troodon",
        image: "troodon.png",
        loot: "TROODONHEADARMARMLEGLEG",
        hp: 200,
        maxHp: 200,
        armor: 5,
        dodge: 10,
        speed: 6,
        resistance: 5,
        attacks: [{name: "Bite", dmg: 40}, {name: "slash", dmg: 30}],
    },
];