//enemyArray
export default [
    {
        name: "Oviraptor",
        image: "oviraptor.png",
        loot: "OVIRAPTORLEGLEGARMARMTAILHEADCREST",
        hp: 200,
        maxHp: 200,
        armor: 2,
        dodge: 10,
        speed: 5,
        resistance: 5,
        attacks: [{name: "slash", dmg: 20}, {name: "bite", dmg: 30}],
    },
    {
        name: "Ankylosaurus",
        image: "Anky.png",
        loot: "ANKYLOSAURUSHEADLEGLEGLEGLEG",
        hp: 400,
        maxHp: 400,
        armor: 20,
        dodge: 0,
        speed: 4,
        resistance: 10,
        attacks: [{name: "Bash", dmg: 20}, {name: "Bludgeon", dmg: 30}],
    },
    {
        name: "Archaeopteryx",
        image: "oviraptor.png",
        loot: "ARCHAEOPTERYXHEADWINGWINGLEGLEG",
        hp: 250,
        maxHp: 250,
        armor: 2,
        dodge: 20,
        speed: 7,
        resistance: 5,
        attacks: [{name: "slash", dmg: 20}, {name: "peck", dmg: 30}],
    },
    {
        name: "Brachiosaurus",
        image: "oviraptor.png",
        loot: "BRACHIOSAURUSBRACHIOSAURUSLEGLEGLEGLEG",
        hp: 800,
        maxHp: 800,
        armor: 2,
        dodge: 0,
        speed: 2,
        resistance: 20,
        attacks: [{name: "Stomp", dmg: 30}, {name: "tail smash", dmg: 40}],
    },
];